/* Este último ejercicio es un poco especial, aquí todo suma puntos. Tienes 40 minutos para hacer el ejercicio, cuantas más cosas hechas tengas correctamente, más puntos tendrás. Así que es una buena oportunidad para recuperar puntos.

Ejercicio Final.- Cuando el jugador coloque el cursor sobre el texto “Mostrar Pista”, 
tendrá que mostrarse en el elemento con el id pista un texto con una pista, la que vosotros queráis. Y cuando lo retire, 
el mensaje debe desaparecer.MOUSE OVER

Pista: Existen dos eventos llamados mouseover y mouseout, que se activan cuando el usuario coloca o retira el cursor de un elemento HTML.

Extra: Si el jugador ha ganado, el mensaje de la pista cambiará a tener un color de fondo verde y dirá “Ya no necesitas pistas”

Tabla Puntuación

Que el mensaje aparezca cuando el jugador coloca el cursor encima de “Mostrar Pista”

10 Puntos

Que el mensaje desaparezca cuando el jugador coloca el cursor encima de “Mostrar Pista”

10 Puntos

Cambiar el color de fondo del mensaje la haber ganado y coloca el cursor sobre “Mostrar Pista”

5 Puntos

Cambiar la pista una vez el jugador haya ganado*/